-- +goose Up

ALTER TABLE component_repo.part_library_versions
    ADD COLUMN preview_ready boolean NOT NULL DEFAULT false,
    ADD COLUMN relation_ready boolean NOT NULL DEFAULT false,
    ADD COLUMN connector_source_hash text,
    ADD COLUMN connector_parser_version text,
    ADD COLUMN collider_count integer NOT NULL DEFAULT 0,
    ADD COLUMN collider_source_hash text,
    ADD COLUMN collider_parser_version text,
    ADD CONSTRAINT part_library_versions_connector_hash_check CHECK (
        connector_source_hash IS NULL OR connector_source_hash ~ '^[0-9a-f]{64}$'
    ),
    ADD CONSTRAINT part_library_versions_collider_count_check CHECK (collider_count >= 0),
    ADD CONSTRAINT part_library_versions_collider_hash_check CHECK (
        collider_source_hash IS NULL OR collider_source_hash ~ '^[0-9a-f]{64}$'
    ),
    ADD CONSTRAINT part_library_versions_relation_ready_check CHECK (
        NOT relation_ready OR (
            connector_count > 0
            AND connector_source_hash IS NOT NULL
            AND connector_parser_version IS NOT NULL
        )
    );

UPDATE component_repo.part_library_versions version
SET preview_ready = EXISTS (
        SELECT 1
        FROM component_repo.part_geometries geometry
        WHERE geometry.part_library_version_id = version.id
          AND geometry.geometry_status = 'ready'
    ),
    relation_ready = version.connector_count > 0,
    connector_source_hash = CASE WHEN version.connector_count > 0 THEN version.source_hash END,
    connector_parser_version = CASE WHEN version.connector_count > 0 THEN 'legacy-imported-v1' END;

CREATE UNIQUE INDEX part_library_versions_single_active_idx
    ON component_repo.part_library_versions (status)
    WHERE status = 'active';

CREATE TABLE component_repo.part_collider_definitions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_library_version_id uuid NOT NULL REFERENCES component_repo.part_library_versions(id) ON DELETE CASCADE,
    source_collider_id bigint NOT NULL,
    ldraw_part_num text NOT NULL,
    collider_kind text NOT NULL,
    position double precision[] NOT NULL,
    orientation double precision[] NOT NULL,
    half_extents double precision[] NOT NULL,
    raw_params jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (part_library_version_id, source_collider_id),
    CONSTRAINT part_collider_definitions_position_check CHECK (cardinality(position) = 3),
    CONSTRAINT part_collider_definitions_orientation_check CHECK (cardinality(orientation) = 9),
    CONSTRAINT part_collider_definitions_half_extents_check CHECK (
        cardinality(half_extents) = 3
        AND half_extents[1] >= 0
        AND half_extents[2] >= 0
        AND half_extents[3] >= 0
    ),
    CONSTRAINT part_collider_definitions_raw_params_check CHECK (jsonb_typeof(raw_params) = 'object')
);

CREATE INDEX part_collider_definitions_part_idx
    ON component_repo.part_collider_definitions (part_library_version_id, ldraw_part_num);

ALTER TABLE component_repo.part_collider_definitions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON component_repo.part_collider_definitions FROM PUBLIC;

-- +goose Down

DROP TABLE IF EXISTS component_repo.part_collider_definitions;
DROP INDEX IF EXISTS component_repo.part_library_versions_single_active_idx;

ALTER TABLE component_repo.part_library_versions
    DROP CONSTRAINT IF EXISTS part_library_versions_relation_ready_check,
    DROP CONSTRAINT IF EXISTS part_library_versions_collider_hash_check,
    DROP CONSTRAINT IF EXISTS part_library_versions_collider_count_check,
    DROP CONSTRAINT IF EXISTS part_library_versions_connector_hash_check,
    DROP COLUMN IF EXISTS collider_parser_version,
    DROP COLUMN IF EXISTS collider_source_hash,
    DROP COLUMN IF EXISTS collider_count,
    DROP COLUMN IF EXISTS connector_parser_version,
    DROP COLUMN IF EXISTS connector_source_hash,
    DROP COLUMN IF EXISTS relation_ready,
    DROP COLUMN IF EXISTS preview_ready;
