"""Configuration keys for the Component Repo module."""

COMPONENT_REPO_DATABASE_CONFIG = {
    "artifact_table": "component_artifacts",
    "import_table": "component_imports",
    "scene_snapshot_table": "component_scene_snapshots",
    "candidate_table": "component_candidates",
    "part_library_version_table": "part_library_versions",
    "part_connector_definition_table": "part_connector_definitions",
    "relation_candidate_table": "component_relation_candidates",
    "assembly_relation_table": "component_assembly_relations",
    "component_table": "components",
    "component_version_table": "component_versions",
    "component_interface_table": "component_interfaces",
    "validation_report_table": "component_validation_reports",
    "string_lengths": {
        "id": 36,
        "artifact_type": 32,
        "provider": 32,
        "bucket": 128,
        "sha256": 64,
        "mime_type": 128,
        "status": 32,
        "schema": 64,
        "parser_version": 64,
        "connection_type": 64,
        "connector_type": 64,
        "connector_gender": 16,
        "joint_type": 64,
        "method": 64,
        "user": 128,
    },
    "indexes": {
        "artifact_type": "idx_component_artifacts_type",
        "artifact_sha": "idx_component_artifacts_sha256",
        "artifact_uploaded": "idx_component_artifacts_uploaded_at",
        "import_status": "idx_component_imports_status",
        "import_created": "idx_component_imports_created_at",
        "snapshot_import": "idx_component_scene_snapshots_import",
        "snapshot_created": "idx_component_scene_snapshots_created_at",
        "candidate_import": "idx_component_candidates_import",
        "candidate_status": "idx_component_candidates_status",
        "candidate_created": "idx_component_candidates_created_at",
        "part_library_status": "idx_part_library_versions_status",
        "part_connector_definition_version": "idx_part_connector_definitions_version",
        "part_connector_definition_part": "idx_part_connector_definitions_part",
        "part_connector_definition_type": "idx_part_connector_definitions_type",
        "relation_candidate_component": "idx_component_relation_candidates_candidate",
        "relation_candidate_status": "idx_component_relation_candidates_status",
        "assembly_relation_candidate": "idx_component_assembly_relations_candidate",
        "component_status": "idx_components_status",
        "component_category": "idx_components_category",
        "component_version_component": "idx_component_versions_component",
        "component_version_status": "idx_component_versions_status",
        "component_interface_candidate": "idx_component_interfaces_candidate",
        "component_interface_status": "idx_component_interfaces_status",
        "validation_report_candidate": "idx_component_validation_reports_candidate",
        "validation_report_version": "idx_component_validation_reports_version",
    },
}

REQUIRED_COMPONENT_REPO_CONFIG_KEYS = (
    "schema",
    "audit",
    "storage",
    "routes",
    "artifacts",
    "imports",
    "versions",
    "database",
    "errors",
)
