"""Configuration keys for the Component Repo module."""

COMPONENT_REPO_DATABASE_CONFIG = {
    "artifact_table": "component_artifacts",
    "upload_session_table": "component_upload_sessions",
    "import_table": "component_imports",
    "scene_snapshot_table": "component_scene_snapshots",
    "candidate_table": "component_candidates",
    "part_library_version_table": "part_library_versions",
    "part_connector_definition_table": "part_connector_definitions",
    "connector_analysis_table": "component_connector_analyses",
    "connector_analysis_item_table": "component_connector_analysis_items",
    "connector_analysis_path_table": "component_connector_analysis_path_nodes",
    "connector_analysis_blocker_table": "component_connector_analysis_blockers",
    "connector_analysis_relation_table": "component_connector_analysis_relations",
    "relation_candidate_table": "component_relation_candidates",
    "assembly_relation_table": "component_assembly_relations",
    "component_table": "components",
    "component_translation_table": "component_translations",
    "component_group_table": "component_groups",
    "component_group_membership_table": "component_group_memberships",
    "component_subscription_table": "component_subscriptions",
    "component_version_table": "component_versions",
    "component_interface_table": "component_interfaces",
    "validation_report_table": "component_validation_reports",
    "string_lengths": {
        "id": 36,
        "artifact_type": 32,
        "provider": 32,
        "bucket": 128,
        "sha256": 64,
        "mime_type": 128,
        "status": 32,
        "schema": 64,
        "parser_version": 64,
        "connection_type": 64,
        "connector_type": 64,
        "connector_gender": 16,
        "joint_type": 64,
        "method": 64,
        "user": 128,
    },
    "indexes": {
        "artifact_type": "idx_component_artifacts_type",
        "artifact_sha": "idx_component_artifacts_sha256",
        "artifact_uploaded": "idx_component_artifacts_uploaded_at",
        "upload_session_owner": "idx_component_upload_sessions_owner",
        "upload_session_status": "idx_component_upload_sessions_status",
        "upload_session_created": "idx_component_upload_sessions_created_at",
        "import_status": "idx_component_imports_status",
        "import_created": "idx_component_imports_created_at",
        "snapshot_import": "idx_component_scene_snapshots_import",
        "snapshot_created": "idx_component_scene_snapshots_created_at",
        "candidate_import": "idx_component_candidates_import",
        "candidate_status": "idx_component_candidates_status",
        "candidate_created": "idx_component_candidates_created_at",
        "part_library_status": "idx_part_library_versions_status",
        "part_connector_definition_version": "idx_part_connector_definitions_version",
        "part_connector_definition_part": "idx_part_connector_definitions_part",
        "part_connector_definition_type": "idx_part_connector_definitions_type",
        "connector_analysis_item_candidate_state": "idx_component_connector_analysis_items_candidate_state",
        "connector_analysis_item_candidate_part": "idx_component_connector_analysis_items_candidate_part",
        "connector_analysis_path_instance": "idx_component_connector_analysis_path_instance",
        "connector_analysis_blocker_part": "idx_component_connector_analysis_blocker_part",
        "connector_analysis_relation_relation": "idx_component_connector_analysis_relation_relation",
        "relation_candidate_component": "idx_component_relation_candidates_candidate",
        "relation_candidate_status": "idx_component_relation_candidates_status",
        "assembly_relation_candidate": "idx_component_assembly_relations_candidate",
        "component_status": "idx_components_status",
        "component_deleted": "idx_components_deleted",
        "component_category": "idx_components_category",
        "component_logical_size": "idx_components_logical_size",
        "component_translation_locale": "idx_component_translations_locale",
        "component_translation_status": "idx_component_translations_status",
        "component_group_owner_parent_sort": "idx_component_groups_owner_parent_sort",
        "component_group_root_owner": "uq_component_groups_root_owner",
        "component_group_membership_component": "idx_component_group_memberships_component",
        "component_subscription_component": "idx_component_subscriptions_component",
        "component_version_component": "idx_component_versions_component",
        "component_version_status": "idx_component_versions_status",
        "component_version_deleted": "idx_component_versions_deleted",
        "component_version_preview_artifact": "idx_component_versions_preview_artifact",
        "component_version_preview_status": "idx_component_versions_preview_status",
        "component_interface_candidate": "idx_component_interfaces_candidate",
        "component_interface_status": "idx_component_interfaces_status",
        "validation_report_candidate": "idx_component_validation_reports_candidate",
        "validation_report_version": "idx_component_validation_reports_version",
    },
}

REQUIRED_COMPONENT_REPO_CONFIG_KEYS = (
    "schema",
    "audit",
    "storage",
    "routes",
    "artifacts",
    "imports",
    "interface_recognition",
    "versions",
    "database",
    "errors",
)
